# Form implementation generated from reading ui file '.\QtUI\ui_about_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ui_AboutDialog(object):
    def setupUi(self, ui_AboutDialog):
        ui_AboutDialog.setObjectName("ui_AboutDialog")
        ui_AboutDialog.resize(359, 41)
        self.label = QtWidgets.QLabel(ui_AboutDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 152, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(ui_AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(ui_AboutDialog)

    def retranslateUi(self, ui_AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        ui_AboutDialog.setWindowTitle(_translate("ui_AboutDialog", "About"))
        self.label.setText(_translate("ui_AboutDialog", "Hello there, I\'m Developer"))
